### ISSUE TITLE
下载解压之后无法使用是什么原因 我都把层级目录都一样的了

### ISSUE THREAD

**Issue by wuao** [otale/theme_handsome#1]
![image](https://user-images.githubusercontent.com/12946169/32491918-0994fe42-c37e-11e7-8e26-d57d5b4c3f10.png)

![image](https://user-images.githubusercontent.com/12946169/32491854-d69f2dd2-c37d-11e7-956a-0836d7d9d36f.png)

![image](https://user-images.githubusercontent.com/12946169/32491929-1140957a-c37e-11e7-9772-c439f9ecf4ed.png)

 

在主题后台设置中不会显示出预览

**Comment by hongquan66** [comment]
@wuao 请提供 tale 具体的版本

**Comment by wuao** [comment]
最新版本号0.0.4
![image](https://user-images.githubusercontent.com/12946169/32493551-d9681424-c383-11e7-9e79-9ecff8b83ee1.png)

**Comment by hongquan66** [comment]
@wuao 我这边尽快测试好告诉你

**Comment by wuao** [comment]
ok

**Comment by hongquan66** [comment]
@wuao 因为当初 handsome 主题是基于 tale-mysql 的版本搭建的，tale-sqlite 一直没有测试，而且两个版本的代码存在一定差异，近期我会发布主题兼容 tale-sqlite 版本的主题，请留意

**Comment by hongquan66** [comment]
@wuao handsome 主题已更新
