### ISSUE TITLE
查看文章，模板参数解析错误

### ISSUE THREAD

**Issue by wayn111** [otale/theme_handsome#4]
### partial\comments.html文件81行：
`<input id="url" class="form-control" name="url" type="url" value="${login_user.home_url ?! ''}" maxlength="200" placeholder="网站或博客">`

value="${login_user.home_url ?! ''}" 改为**value="${login_user.homeUrl ?! ''}"**

**Comment by hongquan66** [comment]
感谢反馈，因为 tale 版本不断迭代的关系，有些较老的属性在新版本中做了调整，我会抽空更新上去，在此之前只能靠大家手动修改一下 😖
